# Generated by Django 2.2.1 on 2019-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrank',
            name='yoe',
            field=models.IntegerField(default=0),
        ),
    ]
