# Generated by Django 2.2.1 on 2019-05-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0002_refrank_yoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmaster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
