# Generated by Django 2.2.1 on 2019-05-27 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps_core', '0003_auto_20190527_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='refrank',
            unique_together={('yoe', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='skillmaster',
            unique_together={('skill', 'user')},
        ),
    ]
