# Generated by Django 2.2.1 on 2019-05-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0004_auto_20190527_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefRank',
            new_name='ReferenceRank',
        ),
    ]
