# Generated by Django 2.2.1 on 2019-05-30 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps_core', '0005_auto_20190527_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1023)),
                ('comment', models.CharField(max_length=1023)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rank_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_core.Rank')),
                ('skill_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_core.SkillMaster')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps_core.Status')),
            ],
        ),
    ]
