# Generated by Django 2.2.1 on 2019-05-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0006_status_updaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Denied')]),
        ),
    ]
