# Generated by Django 2.2.1 on 2019-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0007_auto_20190530_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='code',
        ),
    ]
