# Generated by Django 2.2.1 on 2019-05-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0010_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ps_core.Status'),
            preserve_default=False,
        ),
    ]
