# Generated by Django 2.2.1 on 2019-05-30 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0011_updaterequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='date_app',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='approved date'),
        ),
    ]
