# Generated by Django 2.2.1 on 2019-05-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0012_updaterequest_date_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='rank_cur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='ps_core.Rank'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='rank_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_rank', to='ps_core.Rank'),
        ),
    ]
