# Generated by Django 2.2.1 on 2019-06-01 12:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0013_auto_20190530_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterequest',
            name='date_req',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='request date'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='rank_cur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rank', to='ps_core.Rank', verbose_name='current rank'),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='rank_req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_rank', to='ps_core.Rank', verbose_name='request rank'),
        ),
    ]
