# Generated by Django 2.2.1 on 2019-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0014_auto_20190601_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='comment',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
