# Generated by Django 2.2.1 on 2019-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0016_auto_20190602_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('skill', models.ManyToManyField(to='ps_core.Skill')),
            ],
        ),
    ]
