# Generated by Django 2.2.1 on 2019-06-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0017_skillgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillgroup',
            old_name='skill',
            new_name='skill_set',
        ),
    ]
