# Generated by Django 2.2.1 on 2019-06-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0018_auto_20190613_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='upper_skill_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ps_core.SkillGroup'),
        ),
        migrations.RemoveField(
            model_name='skillgroup',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='skillgroup',
            name='skill_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ps_core.Skill'),
        ),
    ]
