# Generated by Django 2.2.1 on 2019-06-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0020_auto_20190629_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgroup',
            name='upper_skill_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_skill_group_set', to='ps_core.SkillGroup'),
        ),
    ]
