# Generated by Django 2.2.1 on 2019-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default='unit1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
