# Generated by Django 2.2.1 on 2019-06-05 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
