# Generated by Django 2.2.1 on 2019-06-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_unit_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
