# Generated by Django 2.2.1 on 2019-06-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='upper_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_unit_set', to='users.Unit'),
        ),
    ]
