# Generated by Django 2.2.1 on 2019-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190605_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approver',
            field=models.BooleanField(default=False, verbose_name='approver'),
        ),
    ]
