# Generated by Django 2.2.1 on 2019-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_core', '0022_auto_20190629_0259'),
        ('users', '0014_auto_20190613_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skill_group_follow',
            field=models.ManyToManyField(to='ps_core.SkillGroup'),
        ),
    ]
